window.esdocSearchIndex = [
  [
    "redux-addons/lib/store.js~configurebrowserstateaccessor",
    "variable/index.html#static-variable-configureBrowserStateAccessor",
    "<span>configureBrowserStateAccessor</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~configurebrowserstore",
    "variable/index.html#static-variable-configureBrowserStore",
    "<span>configureBrowserStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/context.js~configurecontext",
    "function/index.html#static-function-configureContext",
    "<span>configureContext</span> <span class=\"search-result-import-path\">redux-addons/lib/context.js</span>",
    "function"
  ],
  [
    "redux-addons/lib/store.js~configurelocalstateaccessor",
    "variable/index.html#static-variable-configureLocalStateAccessor",
    "<span>configureLocalStateAccessor</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~configurelocalstore",
    "variable/index.html#static-variable-configureLocalStore",
    "<span>configureLocalStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~configurereducer",
    "variable/index.html#static-variable-configureReducer",
    "<span>configureReducer</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~configuresessionstateaccessor",
    "variable/index.html#static-variable-configureSessionStateAccessor",
    "<span>configureSessionStateAccessor</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~configuresessionstore",
    "variable/index.html#static-variable-configureSessionStore",
    "<span>configureSessionStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createactionmultiplexer",
    "variable/index.html#static-variable-createActionMultiplexer",
    "<span>createActionMultiplexer</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createjsonlocalstore",
    "variable/index.html#static-variable-createJSONLocalStore",
    "<span>createJSONLocalStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createjsonsessionstore",
    "variable/index.html#static-variable-createJSONSessionStore",
    "<span>createJSONSessionStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createlocalstore",
    "variable/index.html#static-variable-createLocalStore",
    "<span>createLocalStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/log.js~createlogger",
    "variable/index.html#static-variable-createLogger",
    "<span>createLogger</span> <span class=\"search-result-import-path\">redux-addons/lib/log.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createmergingreducer",
    "variable/index.html#static-variable-createMergingReducer",
    "<span>createMergingReducer</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createnoopstore",
    "variable/index.html#static-variable-createNoopStore",
    "<span>createNoopStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~createsessionstore",
    "variable/index.html#static-variable-createSessionStore",
    "<span>createSessionStore</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "redux-addons/lib/store.js~toconstcase",
    "variable/index.html#static-variable-toConstCase",
    "<span>toConstCase</span> <span class=\"search-result-import-path\">redux-addons/lib/store.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/context.js",
    "file/lib/context.js.html",
    "lib/context.js",
    "file"
  ],
  [
    "lib/context.js~appopts",
    "typedef/index.html#static-typedef-AppOpts",
    "lib/context.js~AppOpts",
    "typedef"
  ],
  [
    "lib/context.js~appvalidator",
    "typedef/index.html#static-typedef-AppValidator",
    "lib/context.js~AppValidator",
    "typedef"
  ],
  [
    "lib/context.js~createcontext",
    "typedef/index.html#static-typedef-CreateContext",
    "lib/context.js~CreateContext",
    "typedef"
  ],
  [
    "lib/context.js~libaction",
    "typedef/index.html#static-typedef-LibAction",
    "lib/context.js~LibAction",
    "typedef"
  ],
  [
    "lib/context.js~libactions",
    "typedef/index.html#static-typedef-LibActions",
    "lib/context.js~LibActions",
    "typedef"
  ],
  [
    "lib/context.js~libcontext",
    "typedef/index.html#static-typedef-LibContext",
    "lib/context.js~LibContext",
    "typedef"
  ],
  [
    "lib/context.js~libcontext",
    "typedef/index.html#static-typedef-LibContext",
    "lib/context.js~LibContext",
    "typedef"
  ],
  [
    "lib/context.js~libopts",
    "typedef/index.html#static-typedef-LibOpts",
    "lib/context.js~LibOpts",
    "typedef"
  ],
  [
    "lib/log.js",
    "file/lib/log.js.html",
    "lib/log.js",
    "file"
  ],
  [
    "lib/store.js",
    "file/lib/store.js.html",
    "lib/store.js",
    "file"
  ]
]